export const stageData = {
  1: {
    name: '벙커 외곽',
    description: '폐허가 된 도시의 변두리',
    theme: '돌연변이와 약탈자',
    combatPool: ['marauder1', 'marauder2', 'infectedDog'],
    miniboss: 'marauderLeader',
    boss: 'lumenReaper',
    eventPool: ['event_supplies', 'event_survivor', 'event_trap'],
    shopType: 'basic',
  },
  2: {
    name: '중립 지대',
    description: '빛을 먹은 식물과 이상 현상이 엉킨 구역',
    theme: '빛을 먹은 식물과 이상 현상',
    combatPool: ['shadowWraith', 'doppelganger', 'unpleasantCube'],
    miniboss: 'subject162',
    boss: 'chimera',
    eventPool: ['event_coin_pouch', 'event_wishing_well', 'event_supplies'],
    shopType: 'basic',
  },
  3: {
    name: '최종 심층',
    description: '동전 기반 전투 그룹이 기다리는 최종 구역',
    theme: '동전 기반 이벤트 및 전투 그룹',
    combatPool: [],
    miniboss: '',
    boss: '',
    eventPool: [],
    shopType: 'basic',
  },
};
