import {
  PatternUpgradeDefinition,
  CharacterClass,
} from "./types";

export const patternUpgrades: { [key in CharacterClass]?: { [id: string]: PatternUpgradeDefinition } } = {
  [CharacterClass.WARRIOR]: {
    'WARRIOR_PASSIVE_LOSE_HP_GAIN_AMP': { id: 'WARRIOR_PASSIVE_LOSE_HP_GAIN_AMP', name: "소음 유발 장치", description: "매 턴 체력을 1 잃고, 증폭을 1 얻습니다.", cost: { senseFragments: 3 } },
    'WARRIOR_PASSIVE_NO_ATTACK_GAIN_AMP': { id: 'WARRIOR_PASSIVE_NO_ATTACK_GAIN_AMP', name: "A S M R", description: "한 턴 동안 공격을 하지 않으면 증폭을 2 얻습니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_AMP_GIVES_DEF': { id: 'WARRIOR_PASSIVE_AMP_GIVES_DEF', name: "공방일체", description: "이제 증폭으로 추가 방어력을 같이 얻습니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_AMP_BONUS_UP': { id: 'WARRIOR_PASSIVE_AMP_BONUS_UP', name: "초진동 증폭 장치 : E.C.H.O", description: "이제 증폭으로 얻는 추가 능력치가 1 증가합니다.", cost: { senseFragments: 5 } },
    'WARRIOR_PASSIVE_MAX_AMP_20': { id: 'WARRIOR_PASSIVE_MAX_AMP_20', name: "진동 충전지", description: "이제 증폭 상한치가 20 까지 증가합니다.", cost: { senseFragments: 5 } },
    'WARRIOR_PASSIVE_RESONANCE_DURATION': { id: 'WARRIOR_PASSIVE_RESONANCE_DURATION', name: "공명 지속 장치", description: "적에게 부여된 공명의 지속 시간이 3 턴으로 늘어난다.", cost: { senseFragments: 3 } },
    'WARRIOR_PASSIVE_HEADS_GIVE_RESONANCE': { id: 'WARRIOR_PASSIVE_HEADS_GIVE_RESONANCE', name: "공명 전이 발생기", description: "매 턴, 앞면이 3 이상일 경우 적에게 공명을 1 부여합니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_ATTACKS_GIVE_RESONANCE': { id: 'WARRIOR_PASSIVE_ATTACKS_GIVE_RESONANCE', name: "자가 공명 기능", description: "이번 전투에 공격 스킬을 3 번 사용할 때 마다 공명을 5 부여합니다.", cost: { senseFragments: 5 } },
    'WARRIOR_PASSIVE_RESONANCE_HEAL': { id: 'WARRIOR_PASSIVE_RESONANCE_HEAL', name: "비명 수집가", description: "공명으로 준 피해의 20% 만큼 체력을 회복합니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_START_RESONANCE': { id: 'WARRIOR_PASSIVE_START_RESONANCE', name: "공명 동기화", description: "전투 시작 시 상대방에게 공명을 2 부여한 상태로 시작합니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_KILL_MAX_HP': { id: 'WARRIOR_PASSIVE_KILL_MAX_HP', name: "피 주머니", description: "적을 처치할 때 마다 최대 체력을 5 얻습니다.", cost: { senseFragments: 4 } },
    'WARRIOR_PASSIVE_BLEED_GIVES_ATK': { id: 'WARRIOR_PASSIVE_BLEED_GIVES_ATK', name: "고통과 쾌락", description: "자신의 출혈 수치만큼 추가 공격력을 1 얻습니다.", cost: { senseFragments: 5 } },
    'WARRIOR_PASSIVE_HIGH_AMP_GIVES_BLEED': { id: 'WARRIOR_PASSIVE_HIGH_AMP_GIVES_BLEED', name: "초진동 돌풍", description: "증폭이 5 이상일 때 매 턴 출혈을 1 얻습니다.", cost: { senseFragments: 3 } },
    'WARRIOR_PASSIVE_SHARE_BLEED_DMG': { id: 'WARRIOR_PASSIVE_SHARE_BLEED_DMG', name: "비명 이중주", description: "자신의 출혈 피해을 적에게도 전달합니다.", cost: { senseFragments: 5 } },
    'WARRIOR_PASSIVE_LOW_HP_GAIN_AMP': { id: 'WARRIOR_PASSIVE_LOW_HP_GAIN_AMP', name: "고행", description: "체력이 50% 이하면 증폭을 3 얻습니다.", cost: { senseFragments: 4 } },
  },
  [CharacterClass.ROGUE]: {
    // Base Passives
    'ROGUE_P_ADRENALINE': { id: "ROGUE_P_ADRENALINE", name: "아드레날린", description: "앞면 확률이 10% 증가합니다.", cost: { senseFragments: 3 } },
    'ROGUE_P_HUNT_FLOW': { id: "ROGUE_P_HUNT_FLOW", name: "사냥의 흐름", description: "추적이 6 이상인 경우, 다음 턴 뒷면 1 개를 앞면으로 바꿉니다. 이 효과는 한 전투 당 한 번만 사용할 수 있습니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_DUAL_WIELD': { id: "ROGUE_P_DUAL_WIELD", name: "쌍권총 마스터", description: "앞으로 추적을 2 번 발동하고, 수치를 6 잃습니다.", cost: { senseFragments: 5 } },
    'ROGUE_P_KILLER_MINDSET': { id: "ROGUE_P_KILLER_MINDSET", name: "킬러의 마음가짐", description: "피격 시 추적을 2 얻습니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_GUN_KATA': { id: "ROGUE_P_GUN_KATA", name: "건 카타", description: "턴 시작 시 나온 앞면 개수당 추적을 얻습니다.", cost: { senseFragments: 5 } },
    // Bleed Synergy Passives
    'ROGUE_P_HUNT_INSTINCT': { id: "ROGUE_P_HUNT_INSTINCT", name: "사냥 본능", description: "추적 피해를 줄 때 마다 출혈을 1 부여합니다.", cost: { senseFragments: 3 } },
    'ROGUE_P_WOUND_TEAR': { id: "ROGUE_P_WOUND_TEAR", name: "상처 찢기", description: "출혈 피해를 2 번 반복합니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_LIFE_STEAL': { id: "ROGUE_P_LIFE_STEAL", name: "생명력 강탈", description: "출혈 피해의 10% 만큼 체력을 회복합니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_BLOOD_BULLET': { id: "ROGUE_P_BLOOD_BULLET", name: "피로 벼려낸 탄환", description: "출혈 피해를 줄 때 마다 추적을 1 얻습니다.", cost: { senseFragments: 5 } },
    'ROGUE_P_BLOOD_FESTIVAL': { id: "ROGUE_P_BLOOD_FESTIVAL", name: "피의 축제", description: "상대방의 출혈이 6 이상인 경우 추가 피해를 2 줍니다.", cost: { senseFragments: 5 } },
    // Shatter Synergy Passives
    'ROGUE_P_WEAKNESS_TRACK': { id: "ROGUE_P_WEAKNESS_TRACK", name: "약점 추적", description: "상대방의 방어가 5 이하인 경우, 스킬 피해가 30%(소수점 버림) 만큼 증가합니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_STENCH_SPRAYER': { id: "ROGUE_P_STENCH_SPRAYER", name: "악취 분사기", description: "매 턴 뒷면 개수만큼 분쇄를 부여합니다.", cost: { senseFragments: 3 } },
    'ROGUE_P_BULLETPROOF_VEST': { id: "ROGUE_P_BULLETPROOF_VEST", name: "방탄 조끼", description: "얻는 방어가 2 증가합니다.", cost: { senseFragments: 5 } },
    'ROGUE_P_SCENT_SCOPE': { id: "ROGUE_P_SCENT_SCOPE", name: "채취 추적 조준경", description: "부여하는 분쇄가 1 증가합니다.", cost: { senseFragments: 4 } },
    'ROGUE_P_SMOKE_BOMB': { id: "ROGUE_P_SMOKE_BOMB", name: "연막탄", description: "상대방의 분쇄가 5 이상인 경우, 방어를 3 얻습니다.", cost: { senseFragments: 4 } },
  },
  [CharacterClass.TANK]: {
    'TANK_P_ABSORB_DEFENSE': { id: "TANK_P_ABSORB_DEFENSE", name: "방어 흡수", description: "상대방의 방어를 파괴할 경우 방어를 3 얻습니다.", cost: { senseFragments: 3 } },
    'TANK_P_HP_TRAINING': { id: "TANK_P_HP_TRAINING", name: "기초 체력 훈련", description: "전투 종료 후 최대 체력이 1 증가합니다. (최대 10)", cost: { senseFragments: 4 } },
    'TANK_P_IMPLANT': { id: "TANK_P_IMPLANT", name: "기초적인 임플란트", description: "기본 피해와 방어가 6만큼 증가합니다.", cost: { senseFragments: 5 } },
    'TANK_P_BACKHAND_UP': { id: "TANK_P_BACKHAND_UP", name: "손등 강화", description: "뒷면이 나올 때 마다 반격을 얻습니다.", cost: { senseFragments: 4 } },
    'TANK_P_PREPARED': { id: "TANK_P_PREPARED", name: "준비하는 마음가짐", description: "전투 시작 시 반격을 3 얻습니다.", cost: { senseFragments: 4 } },
    'TANK_P_SHATTER_SEAL': { id: "TANK_P_SHATTER_SEAL", name: "이중극점", description: "상대방에게 분쇄를 부여할 때마다 봉인도 1 부여합니다.", cost: { senseFragments: 4 } },
    'TANK_P_UNIQUE_UP': { id: "TANK_P_UNIQUE_UP", name: "기초 다지기", description: "유일 스킬의 공격/방어를 4 추가합니다.", cost: { senseFragments: 5 } },
    'TANK_P_SHATTER_DEF': { id: "TANK_P_SHATTER_DEF", name: "불어오는 돌풍", description: "분쇄를 1 잃을 때마다 다음 턴에 방어를 3 얻습니다.", cost: { senseFragments: 4 } },
    'TANK_P_SHATTER_DOUBLE': { id: "TANK_P_SHATTER_DOUBLE", name: "칼바람", description: "분쇄 상태의 적이 15% 대신 30% 만큼 방어를 추가로 잃습니다.", cost: { senseFragments: 5 } },
    'TANK_P_KEEP_DEF': { id: "TANK_P_KEEP_DEF", name: "멈추지 않는 폭풍", description: "턴 종료 시 남은 방어가 사라지지 않습니다.", cost: { senseFragments: 5 } },
    'TANK_P_CHAIN_HEAL': { id: "TANK_P_CHAIN_HEAL", name: "구속복", description: "10 이상의 봉인을 5턴 이상 유지 시, 추가 방어를 5 얻습니다. (전투 당 1회)", cost: { senseFragments: 4 } },
    'TANK_P_DEF_TO_SEAL': { id: "TANK_P_DEF_TO_SEAL", name: "속죄의 사슬", description: "턴 종료 후, 자신의 남은 방어 만큼 봉인을 추가로 얻습니다.", cost: { senseFragments: 4 } },
    'TANK_P_SEAL_THORNS': { id: "TANK_P_SEAL_THORNS", name: "가시 달린 사슬", description: "피격 시 자신의 봉인의 30%(소수점 버림) 만큼 추가로 피해를 줍니다.", cost: { senseFragments: 5 } },
    'TANK_P_TAILS_DEF': { id: "TANK_P_TAILS_DEF", name: "되돌아보기", description: "매턴 나오는 뒷면 만큼 추가 방어를 얻습니다.", cost: { senseFragments: 3 } },
    'TANK_P_COMBO_HEAL': { id: "TANK_P_COMBO_HEAL", name: "루틴", description: "연계에 성공할 때 마다 체력을 5 회복합니다.", cost: { senseFragments: 4 } },
  },
  [CharacterClass.MAGE]: {
    'MAGE_P_FEAR': { id: "MAGE_P_FEAR", name: "조여오는 공포", description: "매턴 자신의 저주 수치가 3 이상일 경우 피해를 1 줍니다.", cost: { senseFragments: 3 } },
    'MAGE_P_CURSE_NUKE': { id: "MAGE_P_CURSE_NUKE", name: "강림", description: "자신의 저주 수치가 20 이상일 때, 피해를 자신의 저주*2 만큼 주고, 모든 저주를 잃습니다. (전투 당 1회)", cost: { senseFragments: 5 } },
    'MAGE_P_DEATH_RESIST': { id: "MAGE_P_DEATH_RESIST", name: "죽음 극복", description: "죽음에 달하는 피해를 받을 경우, 모든 상태 효과를 초기화하고, 최대 체력을 50% 만큼 회복합니다.", cost: { senseFragments: 5 } },
    'MAGE_P_TAILS_CURSE': { id: "MAGE_P_TAILS_CURSE", name: "우울과 자책", description: "나오는 뒷면 만큼 자신에게 저주를 부여합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_KILL_HEAL': { id: "MAGE_P_KILL_HEAL", name: "죽음을 대하는 자세", description: "적 처치 시 자신의 남은 저주 수치만큼 체력을 회복합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_DEF_TO_SEAL': { id: "MAGE_P_DEF_TO_SEAL", name: "영혼을 담은 망토", description: "스킬 사용 후, 자신의 남은 방어력 1당 상대방에게 봉인을 1 부여합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_SEAL_EXECUTE': { id: "MAGE_P_SEAL_EXECUTE", name: "나태의 낫", description: "의지 절단 처형 기준이 최대 체력의 5% 대신, 15% 만큼 증가합니다.", cost: { senseFragments: 5 } },
    'MAGE_P_SEAL_DMG_UP': { id: "MAGE_P_SEAL_DMG_UP", name: "약자멸시", description: "상대방의 봉인 수치 만큼 스킬 피해가 1 증가합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_SEAL_DEFENSE': { id: "MAGE_P_SEAL_DEFENSE", name: "강제 방어 명령", description: "상대방의 봉인이 10 이상인 경우 즉시 상대방의 동전을 전부 뒷면으로 바꿉니다. (전투 당 1회)", cost: { senseFragments: 5 } },
    'MAGE_P_WEAK_BLOOD': { id: "MAGE_P_WEAK_BLOOD", name: "쇠약한 피", description: "매턴마다 받은 피해의 절반 만큼 봉인을 부여합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_RESONANCE_DURATION': { id: "MAGE_P_RESONANCE_DURATION", name: "만성 두통", description: "현재 공명 수치가 3이상 유지 시, 공명 발동 효과를 1턴간 연장시킵니다.", cost: { senseFragments: 3 } },
    'MAGE_P_SELF_HATE': { id: "MAGE_P_SELF_HATE", name: "자기 혐오", description: "현재 공명 수치가 6 이상인 경우, 즉시 자신의 공명을 잃습니다. 그리고 자신과 상대에게 피해를 6 만큼 줍니다.", cost: { senseFragments: 4 } },
    'MAGE_P_RESONANCE_SHIELD': { id: "MAGE_P_RESONANCE_SHIELD", name: "무책임한 방벽", description: "피격 시 흡수하는 공명 수치가 10% 만큼 증가합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_TRIPLE_RESONANCE': { id: "MAGE_P_TRIPLE_RESONANCE", name: "끝나지 않는 우울", description: "매턴 3연 족보가 나온 경우, 자신에게 공명을 2 부여합니다.", cost: { senseFragments: 4 } },
    'MAGE_P_RESONANCE_RECOIL': { id: "MAGE_P_RESONANCE_RECOIL", name: "반복되는 자책", description: "공명 피해의 절반 만큼 다시 공명을 부여합니다.", cost: { senseFragments: 5 } },
  },
};